openapi: 3.0.0
info:
  title: kt-aivle-bigProject
  version: 0.0.2
  description: 6반 18조 swagger입니다

servers:
  - url: http://localhost:3000/api

paths:
  /hello:
    $ref: './openapi/paths/hello.yml'

components:
  schemas:
    $ref: './openapi/components/schemas.yml'