name: workflows-go

on:
  push:
    branches: [ main ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            requirements/ai: 'requirements/ai/**'
            requirements/back: 'requirements/back/**'
            requirements/swagger: 'requirements/swagger/**'

  build:
    needs: changes
    if: ${{ needs.changes.outputs.folders != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.changes.outputs.folders) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.folder }}
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bigproj_${{ matrix.folder == 'requirements/ai' && 'ai' || matrix.folder == 'requirements/back' && 'back' || matrix.folder == 'requirements/swagger' && 'swagger' }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bigproj_${{ matrix.folder == 'requirements/ai' && 'ai' || matrix.folder == 'requirements/back' && 'back' || matrix.folder == 'requirements/swagger' && 'swagger' }}:${{ github.sha }}
